---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

upstream_tag_template: common/v{version}

packages:
  containers-common-fedora:
    downstream_package_name: containers-common
    pkg_tool: fedpkg
    specfile_path: common/rpm/containers-common.spec
  containers-common-centos:
    downstream_package_name: containers-common
    pkg_tool: centpkg
    specfile_path: common/rpm/containers-common.spec
  containers-common-eln:
    downstream_package_name: containers-common
    specfile_path: common/rpm/containers-common.spec

srpm_build_deps:
  - git-archive-all
  - make

# https://packit.dev/docs/configuration/actions
# fix-spec-file only operates on copr builds and doesn't affect official distro builds
actions:
  fix-spec-file: "bash .packit-copr-rpm.sh"

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [containers-common-fedora]
    notifications: &ephemeral_build_failure_notification
      failure_comment:
        message: "Packit jobs failed. @containers/packit-build please check."
    enable_net: true
    targets: &fedora_copr_targets
      - fedora-all

  - job: copr_build
    trigger: pull_request
    packages: [containers-common-eln]
    notifications: *ephemeral_build_failure_notification
    enable_net: true
    targets:
      fedora-eln:
        # Need this to fetch go-md2man which is present in koji envs but not by
        # default on copr envs. Also helps to avoid bundling go-md2man in
        # c/common.
        additional_repos:
          - https://kojipkgs.fedoraproject.org/repos/eln-build/latest/x86_64/

  - job: copr_build
    trigger: pull_request
    packages: [containers-common-centos]
    notifications: *ephemeral_build_failure_notification
    enable_net: true
    targets:
      - centos-stream-9
      - centos-stream-10

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    packages: [containers-common-fedora]
    notifications:
      failure_comment:
        message: "podman-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  # All tests specified in the `/plans/` subdir
  # Tests for Fedora
  - job: tests
    trigger: pull_request
    packages: [containers-common-fedora]
    notifications:
      failure_comment:
        message: "Tests failed. @containers/packit-build please check."
    targets: *fedora_copr_targets
    tf_extra_params:
      environments:
        - artifacts:
          - type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/fedora-$releasever/rhcontainerbot-podman-next-fedora-$releasever.repo


  - job: propose_downstream
    trigger: release
    packages: [containers-common-fedora]
    dist_git_branches: &fedora_targets
      - fedora-all

  # Ignore CentOS Stream for now
  - job: propose_downstream
    trigger: ignore
    packages: [containers-common-centos]
    dist_git_branches:
      - c10s
      - c9s

  # Fedora Koji build
  - job: koji_build
    trigger: commit
    packages: [containers-common-fedora]
    sidetag_group: podman-releases
    # Dependencies are not rpm dependencies, but packages that should go in the
    # same bodhi update
    # Ref: https://packit.dev/docs/fedora-releases-guide/releasing-multiple-packages
    dependents:
      - podman
    dist_git_branches: *fedora_targets
