name: validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

env:
  LINT_VERSION: v2.1.6

jobs:
  common-codespell:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./common
    steps:
    - uses: actions/checkout@v4
    - name: install deps
      # Version of codespell bundled with Ubuntu is way old, so use pip.
      run: pip install --break-system-packages codespell==v2.3.0
    - name: run codespell
      run: codespell --dictionary=-
  common-lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./common
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    - name: install deps
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install libseccomp-dev
    - name: lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: "${{ env.LINT_VERSION }}"
        args: --verbose
        working-directory: ./common
    # Extra linters, only checking new code from a pull request.
    - name: lint-extra
      uses: golangci/golangci-lint-action@v8
      with:
        args: --config=.golangci-extra.yml
        version: "${{ env.LINT_VERSION }}"
        only-new-issues: true
        working-directory: ./common

    - name: validate seccomp
      run: ./tools/validate_seccomp.sh ./pkg/seccomp
