---
name: Image - Codespell

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  image-codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./image

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install deps
        # Version of codespell bundled with Ubuntu is way old, so use pip.
        run: pip install --break-system-packages codespell==v2.3.0
      - name: run codespell
        run: codespell --dictionary=-
